name: MobLimiter
version: 1.0
description: Allows you to set a mob limit on your server
author: VicWhiten
website: www.github.com/VicWhiten
main: com.bukkit.vicwhiten.moblimiter.MobLimiter
commands:
  moblimiter:
    description: Use a MobLimiter command
    usage: |
           /<command> [subcommand] [type]
           Example: /<command> setmax 1000- sets the mob max to 1000
           Example: /<command> purge - removes all mobs/creatures
           Example: /<command> addblacklist pig - blacklists pigs from your server
           Example: /<command> removeblacklist pig - allows pigs to spawn on the server